<div id="timelinediv<?php echo item('ID')?>" style="height:200px"></div>
<?php 
$tags =  item("Item Type Metadata","Tag", array("delimiter" => ','));
$query = array('tags' => $tags);
$things = get_items($query);
# now we filter out Items that lack any date
$thingswithdates = array();
foreach ($things as $thing) {
	if ( count(item('Dublin Core', 'Date', array('all' => true), $thing)) > 0 ) {
		array_push($thingswithdates,$thing);
	}
}
createTimeline("timelinediv" . item('ID'),$thingswithdates);
?>
