<div id="timelinediv<?php echo item('ID')?>" style="height:200px"></div>
<?php 
$tags =  item("Item Type Metadata","Tag", array("delimiter" => ','));
$query = array('tags' => $tags);
$items = get_items($query);
# now we filter out Items that lack any date
$itemswithdates = array();
$itemswithoutdates = array();
foreach ($items as $item) {
	if ( count(item('Dublin Core', 'Date', array('all' => true), $item)) > 0 ) {
		//echo("Timeline: Item with dates: " . item('Dublin Core', 'Date', array('all' => true), $thing));
		array_push($itemswithdates,$item);
	}
	else {
		//echo("Timeline: Item with no dates. ");
		array_push($itemswithoutdates,$item);
	}
}
createTimeline("timelinediv" . item('ID'),$itemswithdates);
?>
<div class="thingswithoutdates">
	<ul>
		<?php foreach ($itemswithoutdates as $item) {?>
			<li>
				<ul id="neatline-item-<?php echo $item->id?>" class="neatline-timeless-item" onclick="Omeka.Timeline.behavior(<?php echo $item>id?>)">
					<li>
						Thing: <?php echo $item->id?>
					</li>
					<li>
						Title: <?php echo item("Dublin Core", "Title", array(), $item)?>
					</li>
					<li>
						Description: <?php echo item("Dublin Core", "Description", array(), $item)?>
					</li>
				</ul>
			</li>
		<?php } ?>
	</ul>
</div>
