<?php

$tags = get_tags(array('sort' => 'alpha'), 200);

$funct = create_function('$e', 'return is_array($e) && array_key_exists("name",$e) ? $e["name"] : null;');
$tagnames = array_map($funct, $tags);
//unset($funct); // in case this code is called again later, we don't want to try to define $funct twice

$options = array_combine($tagnames,$tagnames);

?>

<div id="tagtext">
<?php echo $this->formSelect( $inputNameStem . "[text]", $value, array('class'=>'select'), $options); ?>
</div>

