<div>
<?php
/* simple edit panel widget to be swapped in when an editable event 
 * is clicken in a Timeline
 */ 

echo js('tiny_mce/tiny_mce'); 
echo js('items'); 
?>
 
<form method="post" enctype="multipart/form-data" id="item-form" action="">

<span>Editing <?php echo $item->id; ?></span>
<?php 
   
$elements_table = get_db()->getTable('Element');
foreach ($element_names as $element_name) {
	echo display_form_input_for_element(
		$elements_table->findByElementSetNameAndElementName('Dublin Core', $element_name),
		$item);
}
?>
	<!-- submit button for metadata form elements -->
	<div>
    		<?php echo submit(array('name'=>'submit', 'id'=>'save-changes', 'class'=>'submit submit-medium'), 'Save Changes'); ?>
    </div>
</form>
<div id="timeline-edit-panel" class="timeline-panel"> 
<!-- 
	<div id="timeline-metadata-container" class="timeline-panel-section"> 
		<dl id="timeline-metadata"> 
			<?php foreach($element_names as $element_name): ?>
				
				<dt class="timeline-metadata-term timeline-metadata-<?php echo $element_name?>"><?php echo $element_name ?></dt>
				<dd class="timeline-metadata-def timeline-metadata-<?php echo $element_name?> timeline-line-editable"><?php echo item('Dublin Core', $element_name, array(), $item); ?></dd>
			<?php endforeach; ?>
		</dl>
	</div>
 -->
	<div id="timeline-metadata-utils">
		<button class="timeline-button timeline-locate-item" onclick="Omeka.Neatline.jQuery('body').neatline('zoom_only',<?php echo $item->id ?>)">Locate</button>
		
		<button class="timeline-button timeline-record-item">
		<button class="timeline-button timeline-save-item">Save</button> 
		<button class="timeline-button timeline-cancel-item">Cancel</button>
		<?php set_theme_base_uri('admin');
       echo link_to_item("Edit", array(), 'edit');
       revert_theme_base_uri();?>
		<a href="javascript:Omeka.Neatline.jQuery('body').neatline('illustrate',<?php echo $item->id ?>)">Illustrate</a>
		
	</div>
</div>
							
</div>
