<?php
/* simple viewing panel to be swapped in over a presented timeline
 * 
 */

?>

	<div style="position: static; width: 360px">
		<?php if (item_has_thumbnail()): ?>
			<?php echo link_to_item(item_square_thumbnail()); ?>
		<?php endif; ?>
		<div class="timeline-event-bubble-title">
			<?php echo link_to_item(); ?>
		</div>
		<?php foreach ($element_names as $element_name):?>
		<div class="timeline-event-bubble-body">
		<dl>
			<dt><label for="viewpanel-<?php echo $element_name ?>"><?php echo $element_name ?>:</label></dt>
			
			<dd><span id="viewpanel-<?php echo $element_name ?>"><?php echo item('Dublin Core', $element_name, array(), $item); ?></span></dd>
		</dl>
		</div>
		<?php endforeach; ?>
		<div id="timeline-metadata-utils">
			<button class="timeline-button timeline-locate-item" onclick="Omeka.Neatline.jQuery('body').neatline('zoom_only',<?php echo $item->id ?>)">Locate</button>
		</div>
	</div>

<?php 
// echo "Viewing " . $item->id;
// 
// 
// echo "<dl>";
// foreach ($element_names as $element_name) {
// 	echo "<dt>" . $element_name . "</dt><dd>" . item('Dublin Core', $element_name, array(), $item) . "</dd>";
// }
// echo "</dl>";
?>

<!-- <div>
	<?php //echo link_to_item("Metadata",array(),"show",$item)?>
	<a href="">Locate</a>
</div> -->